### ISSUE TITLE
老哥麻烦打扰一下，询问一下运作

### ISSUE THREAD

**Issue by RouJiANG-14** [Water008/duokan#1]
因为没啥代码基础
没看明白cookie是怎么传递的？怎么实现多个帐号的？
老哥能方便告知一下么？
是创建多个名为cookie的 secrets么？还是一个secrets分号间隔开多个cookie就行？？？
万分感谢老哥！！！！希望能得到解答。

**Comment by Water008** [comment]
一行一个cookies
即cookies间用换行来隔开

**Comment by RouJiANG-14** [comment]
谢谢老哥！
